<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Stripe\Stripe;
use Stripe\Charge;
use Stripe\Exception\CardException;

class PaymentController extends Controller
{
    public function processPayment(Request $request)
    {
        // Set your Stripe secret key
        Stripe::setApiKey(env('STRIPE_SECRET'));

        try {
            // Create a charge using the token from the frontend
            $charge = Charge::create([
                'amount' => $request->amount * 100, // Amount in cents
                'currency' => 'usd',
                'source' => $request->token, // Token generated by Stripe.js on the frontend
                'description' => 'Payment for order',
            ]);

            // Payment succeeded
            return response()->json([
                'success' => true,
                'message' => 'Payment successful!',
                'charge' => $charge,
            ]);
        } catch (CardException $e) {
            // Payment failed
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
            ], 400);
        }
    }
}